export const ROUT_KEY = {
  HomeScreen: 'HomeScreen',
  Academy: 'Academy',
  BoxAnimated: 'BoxAnimated',
  IntroReanimated: 'IntroReanimated',
  PanGestureHandler: 'PanGestureHandler',
  BottomSheetModal: 'BottomSheetModal',
  BottomSheetWithFlatList: 'BottomSheetWithFlatList',
  AccountScreen: 'AccountScreen',
  NotfiScreen: 'NotfiScreen',
  PostScreen: 'PostScreen',
  SearchScreen: 'SearchScreen',
  BottomNavigator: 'BottomNavigator',
  ScreenITV: 'ScreenITV',
  ScreenPost: 'ScreenPost',
  ScreenTagged: 'ScreenTagged',
  DrawerNavigator: 'DrawerNavigator',
  SyncedFlatList: 'SyncedFlatList',
  CarouselFlatlist: 'CarouselFlatlist',
  ItemOpaFlatlist: 'ItemOpaFlatlist',
  TouManFlatList: 'TouManFlatList',
  CardContext: 'CardContext',
};
